#!/usr/bin/env python3
# pyright: strict
"""Run a gitlab-ci-local job

Interactively choose one job to run.
Forwards all arguments to gitlab-ci-local.
"""


import json
import subprocess
import sys


def main():
    argv = sys.argv[1:]
    if "-h" in argv or "--help" in argv:
        subprocess.run(["gitlab-ci-local", "--help"])
        return
    jobs = available_jobs()
    job = next((a for a in argv if a in jobs), None) or fzf_ask_job(jobs)
    flags = [a for a in argv if a != job]
    subprocess.run(["gitlab-ci-local"] + flags + [job])


def fzf_ask_job(jobs: set[str]):
    try:
        job = subprocess.check_output(
            ["fzf"],
            input="\n".join(jobs).encode(),
        )
        return job.decode().strip()
    except subprocess.CalledProcessError as error:
        if error.returncode == 130:
            raise KeyboardInterrupt()
        raise


def available_jobs() -> set[str]:
    with subprocess.Popen(
        ["gitlab-ci-local", "--list-json"],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    ) as child:
        if not child.stdout:
            raise Unreachable()
        data = json.load(child.stdout)
        return {j["name"] for j in data}


class Unreachable(BaseException):
    pass


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Keyboard interrupt")
