#!/usr/bin/env bash

GREEN="\e[32m"
BLUE="\e[34m"
RESET="\e[0m"
CLICOLOR="${CLICOLOR:-1}"
for value in 0 never off; do
    if [[ "$CLICOLOR" == "$value" ]]; then
        GREEN=""
        BLUE=""
        RESET=""
        break
    fi
done

jq:entries()
{
    jq -r 'to_entries | .[] | "\(.key): \(.value)"' "$@"
}

main()
{
    jq:entries "$@" | while IFS=": " read -r key value; do
        printf "${GREEN}%s${RESET}: ${BLUE}%s${RESET}\n" "$key" "$value"
    done
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    main "$@"
fi
