#!/usr/bin/env bash

set -euo pipefail

get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ |
        rg -o '(\d+%)' |
        head -n 1
}

cmd="${1:-get}"
case "$cmd" in
toggle)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    status="$(pactl get-sink-mute @DEFAULT_SINK@)"
    notify-send -t 500 "Audio" "$status"
    ;;
up)
    pactl set-sink-volume @DEFAULT_SINK@ +5%
    notify-send -t 500 "Audio" "$(get_volume)"
    ;;
down)
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    status="$(pactl get-sink-volume @DEFAULT_SINK@)"
    notify-send -t 500 "Audio" "$(get_volume)"
    ;;
get)
    notify-send -t 1000 "Audio" "$(get_volume)"
    ;;
help|*)
    echo "Usage: $0 {toggle|up|down|get}"
    if [[ "$cmd" != help ]]; then
        exit 1
    fi
    ;;
esac
